name: PHPUnit

on: [ push, pull_request ]

jobs:
  build:
    name: PHP ${{ matrix.php }} with PHPUnit ${{ matrix.phpunit }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [7.3, 7.4, 8.0, 8.1, 8.2]
        phpunit: ['~9.6.13']
        include:
          - php: 8.1
            phpunit: '10.0.0'
          - php: 8.1
            phpunit: '~10'
          - php: 8.1
            phpunit: 'default'
          - php: 8.2
            phpunit: '10.0.0'
          - php: 8.2
            phpunit: '~10'
          - php: 8.2
            phpunit: 'default'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP ${{ matrix.php }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Use specific PHPUnit version
      if: ${{ matrix.phpunit != 'default' }}
      run: composer require --dev --no-update phpunit/phpunit:${{ matrix.phpunit }}

    - name: Validate composer.json
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('composer.json') }}

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress

    - name: Run PHPUnit
      run: vendor/bin/phpunit --bootstrap vendor/autoload.php tests/
